spring:
  application.name: jpa-encrypt

  jpa:
    hibernate:
      ddl-auto: update

  docker:
    compose:
      lifecycle-management: start-and-stop
      file: ${projectRootDir}/compose.yml

  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: ap-northeast-2
      secretsmanager:
        enabled: true
        endpoint: http://0.0.0.0:4566
  config.import:
    - "optional:aws-secretsmanager:kms-db-secret-key"

kms.db.secret_key: "\${kms-db-secret-key:key-none}"

logging:
  level:
    io.awspring.cloud: DEBUG
    com.amazonaws: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    tutorials.jpa: DEBUG
