server:
  port: 8080

spring:
  application.name: openfeign-querydsl

  jpa:
    hibernate:
      ddl-auto: update

  docker:
    compose:
      lifecycle-management: start-and-stop
      file: ${projectRootDir}/compose.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    tutorials: debug
